# umatobi simulator
#
# Copyright (c) 2012-2019 梅濁酒(=umedoblock)
#
# This software is released under the MIT License.
# https://github.com/umedoblock/umatobi

# Makefile
# Copyright (C) 2008 梅濁酒 umedoblock

CC = gcc
LOADLIBES = -lglut
LOADLIBES = -lglut -lGL
LOADLIBES = -lglut -lGL -lm

all: tes0 tes1 tes2 tes3 tes4 tes5 tes6 tes7 tes7-1 \
		tes8 tes9 tes10 tes11 tes12 tes13 tes14 tes15 \
		tes16 tes17 tes18 tes19 tes20
clean:
	rm -f `find . -name 'tes*.c' -type f | sed -e 's/\.c//'`

tes0:
tes1:
tes2:
tes3:
tes4:
tes5:
tes6:
tes7:
tes7-1:
tes8:
tes9:
tes10:
tes11:
tes12:
tes13:
tes14:
tes15:
tes16:
tes17:
tes18:
tes19:
tes20:
